=== Chu5Cang/Bai_TH_XML/qlsinhvien.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- Kiểu mã và tên dùng chung Khoa va Lop-->
    <xs:simpleType name="MaLopKhoaType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="TenType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]+"/>
            <xs:maxLength value="50"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Kiểu số điện thoại Sinh vien-->
    <xs:simpleType name="PhoneType">
        <xs:restriction base="xs:string">
            <xs:pattern value="0\d{9}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="dssv">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="khoa" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ma" type="MaLopKhoaType"></xs:element>
                            <xs:element name="ten" type="TenType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="lop" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="makhoa" type="MaLopKhoaType"></xs:element>
                            <xs:element name="ma" type="MaLopKhoaType"></xs:element>
                            <xs:element name="ten" type="TenType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="sinhvien" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="malop" type="MaLopKhoaType"></xs:element>
                            <xs:element name="mssv">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="hoten">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="150"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="diachi" type="xs:string"></xs:element>
                            <xs:element name="sdt" type="PhoneType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- Khóa chính -->
        <xs:key name="KhoaKey">
            <xs:selector xpath="khoa"></xs:selector>
            <xs:field xpath="ma"></xs:field>
        </xs:key>
        
        <xs:key name="LopKey">
            <xs:selector xpath="lop"></xs:selector>
            <xs:field xpath="ma"></xs:field>
        </xs:key>
        
        <xs:key name="SinhVienKey">
            <xs:selector xpath="sinhvien"></xs:selector>
            <xs:field xpath="mssv"></xs:field>
        </xs:key>
        
        <!-- Khóa Ngoại -->
        <xs:keyref name="KhoaLopRef" refer="KhoaKey">
            <xs:selector xpath="lop"></xs:selector>
            <xs:field xpath="makhoa"></xs:field>
        </xs:keyref>
        
        <xs:keyref name="LopSinhVienRef" refer="LopKey">
            <xs:selector xpath="sinhvien"></xs:selector>
            <xs:field xpath="malop"></xs:field>
        </xs:keyref>

    </xs:element>
</xs:schema>

=== Chu5Cang/Bai_TH_XML/qlsinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<dssv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="qlsinhvien.xsd">
    <khoa>
        <ma>K001</ma>
        <ten>congnghethongtin</ten>
    </khoa>
    <lop>
        <makhoa>K001</makhoa>
        <ma>L001</ma>
        <ten>kythuatphanmem</ten>
    </lop>
    <lop>
        <makhoa>K001</makhoa>
        <ma>L002</ma>
        <ten>khoahocmaytinh</ten>
    </lop>
    <sinhvien>
        <malop>L001</malop>
        <mssv>KTPM221101</mssv>
        <hoten>Trương Văn A</hoten>
        <email>tva@gmail.com</email>
        <diachi>Cần Thơ</diachi>
        <sdt>0932582774</sdt>
    </sinhvien>
    <sinhvien>
        <malop>L001</malop>
        <mssv>KTPM221102</mssv>
        <hoten>Huỳnh văn A</hoten>
        <email>hva@gmail.com</email>
        <diachi>Cần Thơ</diachi>
        <sdt>0934182234</sdt>
    </sinhvien>
    <sinhvien>
        <malop>L002</malop>
        <mssv>KHMT221101</mssv>
        <hoten>Huỳnh Thị C</hoten>
        <email>htc@gmail.com</email>
        <diachi>Cần Thơ</diachi>
        <sdt>0934185234</sdt>
    </sinhvien>
</dssv>
